name: ${CONTAINER_NAME}
services:
  tailscale-minecraft: 
    image: tailscale/tailscale:stable
    container_name: ${CONTAINER_NAME}_tailscale
    hostname: ${CONTAINER_NAME}
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_USERSPACE=false
    volumes:
      - ./tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    healthcheck:
      test: tailscale status --peers=false --json | grep -q 'Online.*true'

  minecraf-controller:
    build:
      context: ./beef-controller
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}_controller
    depends_on:
      tailscale-minecraft:
        condition: service_healthy
      minecraft-server:
        condition: service_started
    volumes:
      - ./beef-controller/data:/var/beef_controller
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINER_NAME: "${CONTAINER_NAME}" 
    restart: unless-stopped
    network_mode: service:tailscale-minecraft

  minecraft-server:
    image: eclipse-temurin:21
    working_dir: /minecraft
    command:
      - "java"
      - "-Xms${RAM_MIN}G"
      - "-Xmx${RAM_MAX}G"
      - "-jar"
      - "-Dfml.readTimeout=180"
      - "-Dfml.queryResult=confirm"
      - "@java9args.txt"
      - "${SERVER_JAR_NAME}.jar"
      - "nogui"
    labels:
      controlled_by: beef_controller
    container_name: ${CONTAINER_NAME}
    volumes:
      - ${MINECRAFT_DIR}:/minecraft # chicken jockey
      - ${BACKUPS_DIR}:/minecraft/backups # serverutilities backups
    depends_on:
      tailscale-minecraft:
        condition: service_healthy
    restart: unless-stopped
    network_mode: service:tailscale-minecraft

  minecraft-samba:
    image: dockurr/samba
    container_name: ${CONTAINER_NAME}_samba
    environment:
        NAME: "${SMB_DIR_NAME}"
        USER: "${SMB_USERNAME}"
        PASS: "${SMB_PASSWORD}"
    volumes:
        - ${MINECRAFT_DIR}:/storage
    restart: unless-stopped
    depends_on:
      tailscale-minecraft:
        condition: service_healthy
    network_mode: service:tailscale-minecraft